### ISSUE TITLE
Server crashes upon placing Cobblestone into Chisel GUI

### ISSUE THREAD

**Issue by Damonj17** [KnowYourKnot/ChiselDecor#3]
I crashed a server twice running ChiselDecor and several other mod by placing Cobblestone into the Chisel GUI. Any ideas on if we're missing some mod or some such? We don't have CBT installed because we have Sodium. Here's the server log before the crash:
`[27.02 07:41:43] [Server] [Server thread/ERROR]: Encountered an unexpected exception
[27.02 07:41:43] [Server] java.lang.NoSuchMethodErrornet.minecraft.class_5414.method_30206(Ljava/lang/Object;)Ljava/util/Collection;
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.block.ChiselGroupLookup$ChiselGroup.inTags(ChiselGroupLookup.java:127) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.block.ChiselGroupLookup$ChiselGroup.containsItem(ChiselGroupLookup.java:118) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.block.ChiselGroupLookup.getGroup(ChiselGroupLookup.java:71) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.block.ChiselGroupLookup.getBlocksInGroup(ChiselGroupLookup.java:87) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.inventory.ChiselInventory.refresh(ChiselInventory.java:57) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.inventory.ChiselInventory.method_5447(ChiselInventory.java:35) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1735.method_7673(class_1735.java:82) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1703.method_30010(class_1703.java:298) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1703.method_7593(class_1703.java:177) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at com.knowyourknot.chiseldecor.gui.ChiselScreenHandler.method_7593(ChiselScreenHandler.java:109) ~[chiseldecor-1.16.5-1.1.2.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_3244.method_12076(class_3244.java:1373) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_2813.method_12191(class_2813.java:32) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_2813.method_11054(class_2813.java:10) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
[27.02 07:41:43] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[27.02 07:41:43] [Server] [Server thread/ERROR]: This crash report has been saved to: /./crash-reports/crash-2021-02-27_07.41.43-server.txt`

**Comment by KnowYourKnot** [comment]
Just patched this in version 1.1.3 - the method used by Minecraft to get all tags which contain a certain item was client-side only (no idea why) so I implemented a function that should work irrespective of side.
